DROP DATABASE IF EXISTS reviews;
CREATE DATABASE reviews;

\c reviews;

CREATE TABLE review (
  review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INT,
  rating SMALLINT,
  summary VARCHAR,
  recommend BOOLEAN,
  response VARCHAR,
  body VARCHAR,
  date TIMESTAMPTZ,
  reviewer_name VARCHAR,
  helpfulness INT,
  email VARCHAR,
  reported BOOLEAN
);

CREATE TABLE photo (
  photo_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url VARCHAR,
  review_id INT,
  FOREIGN KEY (review_id) 
    REFERENCES review (review_id)
    ON DELETE CASCADE
);

CREATE TABLE characteristic (
  characteristic_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INT,
  category VARCHAR
);

CREATE TABLE reviews_characteristics (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url VARCHAR,
  characteristic_id INT,
  review_id INT,
  value SMALLINT,
  FOREIGN KEY (review_id) 
    REFERENCES review (review_id)
    ON DELETE CASCADE,   
  FOREIGN KEY (characteristic_id) 
    REFERENCES characteristic (characteristic_id)
    ON DELETE CASCADE
);

/*  Execute this file from the command line by typing:
 *    psql -d postgres -U sdc < database/schema.sql
 *  to create the database and the tables.*/